### ISSUE TITLE
Missing binaries under Linux (Ubuntu 14.04)

### ISSUE THREAD

**Issue by Deviluc** [FPtje/gmosh#10]
When I try to install gmosh using the installer script (copied from package/Linux to root dir), I get the following error: "cp: cannot stat ‘bin/*’: No such file or directory"

I previously ran make, which gave me following output:
```
pyside-uic ui/mainwindow.ui -o src/view/mainwindow.py
pyside-uic ui/progressdialog.ui -o src/view/progressdialog.py
```

ls -la /usr/local/bin/ | grep gmosh gives following output:
```
lrwxrwxrwx  1 root root     18 Mai  5 13:38 gmoshui -> /opt/gmosh/gmoshui
```

/opt/gmosh/ however is empty

Using make install_linux to install I get following output:
```
# Desktop and mime files
if [ -L /usr/share/applications/gmoshui.desktop ]; then rm /usr/share/applications/gmoshui.desktop; fi
if [ -L /usr/share/pixmaps/gmosh_256.png ]; then rm /usr/share/pixmaps/gmosh_256.png; fi
if [ -L /usr/bin/gmosh ]; then rm /usr/bin/gmosh; fi
if [ -L /usr/local/bin/gmosh ]; then rm /usr/local/bin/gmosh; fi
if [ -d /opt/gmosh ]; then rm -r /opt/gmosh; fi
if [ -L /usr/lib/libsteam_api.so ]; then rm /usr/lib/libsteam_api.so; fi
if [ -L /usr/lib/libsteam_api.dylib ]; then rm /usr/lib/libsteam_api.dylib; fi
if [ -L /usr/bin/gmpublish_linux ]; then rm /usr/bin/gmpublish_linux; fi
if [ -L /usr/local/bin/gmpublish_linux ]; then rm /usr/local/bin/gmpublish_linux; fi
if [ -L /usr/bin/gmpublish_osx ]; then rm /usr/bin/gmpublish_osx; fi
if [ -L /usr/local/bin/gmpublish_osx ]; then rm /usr/local/bin/gmpublish_osx; fi
if [ ! -d /opt/gmosh ]; then mkdir -p /opt/gmosh; fi
cp -r bin/* /opt/gmosh
cp: cannot stat ‘bin/*’: No such file or directory
make: *** [install_linux] Error 1
```
So I assume there needs to be a directory called bin containing at least one file to satisfy "cp -r bin/* /opt/gmosh".
So doing following steps gets me closer to the solution but I'm still missing gmosh and gmoshui binaries:
```
mkdir bin
cd bin/
cp ../required/* ./
```
sudo make install_linux then gives me follwoing error:
```
chmod: cannot access ‘/opt/gmosh/gmosh’: No such file or directory
```

So my conclusion is that the "prebuilt" package is actually missing the binaries "gmosh" and "gmoshui".

**Comment by Bo98** [comment]
Are you using one of the releases?

https://github.com/FPtje/gmosh/releases

**Comment by FPtje** [comment]
Only the releases have binaries. You can manually run gmosh and gmoshui by running the python scripts in src/ with python3. You'll need a shitload of dependencies, though.

**Comment by Deviluc** [comment]
Well, my fault I just checked out the git repository...

**Comment by FPtje** [comment]
Yeah, it needs to compile.
