### ISSUE TITLE
Addon has invalid type! Error

### ISSUE THREAD

**Issue by TheEMP** [FPtje/gmosh#11]
I've been trying to use gmosh to publish a new addon to the workshop but when ever I click the publish button it fails to upload with the error Addon has invalid type! I've included screen shots of my settings and of the addon.json file for reference.

![Image of errror](http://i.gyazo.com/adb2e8fbd8dffbdffd8accb4b39a22b3.png)
![Image of settings](http://i.gyazo.com/6c26b3610bece24a5b91b5c3637502ea.png)
![Image of settings](http://i.gyazo.com/b9004588a0ec99c4eac1fb8b0f08c139.png)

**Comment by FPtje** [comment]
I hit this while testing your thing:
http://facepunch.com/showthread.php?t=1450721&p=47689508&viewfull=1#post47689508

**Comment by FPtje** [comment]
Ah, managed to reproduce it.

Them sons of bitches say it's "ServerContent", but in the gma it's really "servercontent"

**Comment by FPtje** [comment]
Fixed in this release:
https://github.com/FPtje/gmosh/releases/tag/v2.2.1alpha
