### ISSUE TITLE
Can't parse some workshop info?

### ISSUE THREAD

**Issue by birdbrainswagtrain** [FPtje/gmosh#13]
```
gmosh --workshopinfo 114313290
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "src/gmosh.py", line 342, in <module>
  File "src/gmosh.py", line 54, in main
  File "src/gmosh.py", line 249, in workshopinfo
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 834: invalid continuation byte
```
I found one addon that seems to break gmosh's ballsack. It's not made by wiox so I don't know why it would be doing that. I will investigate further tomorrow once I get my project to download/parse this stuff itself. The offending addon:

http://steamcommunity.com/sharedfiles/filedetails/?id=114313290

**Comment by Bo98** [comment]
There's a Latin-1 character in the description and thus breaks when decoding under UTF-8.

Even the workshop page doesn't like it and is not showing the description.

**Comment by Bo98** [comment]
I've reported it to Valve but whether they read/do anything is another matter.

**Comment by FPtje** [comment]
I'll blame it on Valve not filtering those characters for now. We'll see what valve does to support this.

This is incredible laziness on my part, give me a shout when it's really needed.
