### ISSUE TITLE
Allow being able to choose where to install with installer

### ISSUE THREAD

**Issue by LUModder** [FPtje/gmosh#14]
I prefer to be able to install to my storage drive rather then my SSD for my OS

**Comment by FPtje** [comment]
For now, just change the directories in install.bat. The installer uses that. Another option is to move the folder from program files afterwards, which should work but is definitely less clean.

This is very lazy on my side, but I cannot be bothered to mess with gmosh for this kind of issue. With RB's plans to change the workshop system altogether, gmosh might soon enough become redundant.
