### ISSUE TITLE
Download workshop percentage shows wrong

### ISSUE THREAD

**Issue by Donkie** [FPtje/gmosh#15]
The download progress displays like a fraction but has a % after it. Should probably just multiply the progress by 100.

Looks like: 0.53%
Should be: 53%

Noticed just now that when it's finished downloading it jumps to 100.00% immediately..?

**Comment by FPtje** [comment]
I don't have Python and all that shebang installed. This should fix it, but I'm not going to publish a new version for this one here change :)
