### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by DatAmazingCheese** [FPtje/gmosh#16]
![image](https://cloud.githubusercontent.com/assets/23209028/20645611/9ddd2e7a-b4b7-11e6-9683-775d6098a6a8.png)

This is what I get whenever I open gmoshui. I haven't done anything out of the ordinary to cause it.

I haven't tried restarting or anything of that nature. 

To work around it I just used gmpublish.

A fix to this would be amazing.

**Comment by FPtje** [comment]
What version are you using? Does it happen if you use a different version?

**Comment by DatAmazingCheese** [comment]
I'm using 2.2.1 non alpha.

**Comment by FPtje** [comment]
There's 2.2.1 alpha and 2.1.1 non alpha. Whichever one you're trying, please try the other one.

**Comment by FPtje** [comment]
Closing until it's confirmed to be a problem on my end.
