### ISSUE TITLE
Steam Not Running

### ISSUE THREAD

**Issue by BLEEPBLOOPforLife** [FPtje/gmosh#17]
When I try to publish an addon on Ubuntu 16.04 (Xenial) Server, it tells me that Steam isn't running. I am not using a desktop environment. How do I get Steam to work? I have already tried using SteamCMD in a screen, then running gmosh, but it doesn't work. I entered all of the information it asks, then after it says Creating Temporary GMA, it says Steam isn't running.

**Comment by FPtje** [comment]
Install the actual steam client. The one you play games with.
