### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by Donkie** [FPtje/gmosh#18]
Sounds similar to #16 
Just happened one day, haven't changed installation or anything. Tried reinstalling to both 2.2.1 and 2.1.1
This error pops up whenever I try to start the program.

![http://f.donkie.co/w8k2h](http://f.donkie.co/w8k2h)

**Comment by FPtje** [comment]
What the fuck

**Comment by Donkie** [comment]
I'm on steam right now and I could help you test if you're interested.

**Comment by FPtje** [comment]
Could you try clearing `%APPDATA%/Roaming/QtProject`?

**Comment by Donkie** [comment]
No such folder

**Comment by FPtje** [comment]
Is there any gmosh related folder in the `%APPDATA%/Roaming`?

**Comment by Donkie** [comment]
Sadly, nope

**Comment by FPtje** [comment]
Try these registry paths:

```
HKEY_CURRENT_USER\Software\FPtje\gmoshui
HKEY_CURRENT_USER\Software\FPtje
HKEY_LOCAL_MACHINE\Software\FPtje\gmoshui
HKEY_LOCAL_MACHINE\Software\FPtje
```

**Comment by Donkie** [comment]
found it!

I had changed my garrysmod installation directory (to a new drive), the "lcache" key was still using the old directory. Manually changed the key and it works fine.

**Comment by Donkie** [comment]
Looks like you're returning false here: https://github.com/FPtje/gmosh/blob/4cd8a2504c0be43794b29377c3c0d1ac1e8c301c/src/gmodfolder.py#L34

if the folder doesn't exist, which means you feed a bool into the setRootPath, which produces the error.

**Comment by FPtje** [comment]
I know, but that's not the bit I'm worried about. The bit I'm worried about is re-packaging it. cx_freeze is a total bitch. It'll take hours to set it up and release a new version of gmosh.

**Comment by Donkie** [comment]
rest in peace

**Comment by FPtje** [comment]
Seriously, because of cx_freeze I've decided never to release a cross platform python thing again, unless I can assume everyone has a python interpreter installed.

**Comment by Donkie** [comment]
That's probably easier, I've had to install python separately many times in the past.

**Comment by FPtje** [comment]
For people like you, yes. I sadly can't expect if from the general gmosh userbase.

**Comment by Donkie** [comment]
Are people using gmosh for anything but modding? Can't you just give them a dead simple link to where they get the exe for the correct python version.

**Comment by FPtje** [comment]
Creating the exe is the difficult bit.

**Comment by Donkie** [comment]
Python comes packaged in installable exes?

**Comment by FPtje** [comment]
Oh you meant python itself. It's not only python, but also the dependencies.

**Comment by Donkie** [comment]
I see, idk then.

**Comment by Leapyy** [comment]
Any fixes for this? receiving  the exact same error.

**Comment by FPtje** [comment]
Yes, see above

**Comment by FPtje** [comment]
I'm dropping support for this piece of software. Reproducing a build is just too much damn work. Here's a zip file with a registry thing that clears it. Close gmoshui, run the thing and try to start it again.

[fixerror.zip](https://github.com/FPtje/gmosh/files/761519/fixerror.zip)
