### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by cubic-control** [FPtje/gmosh#19]
![bandicam 2017-06-29 12-39-10-584](https://user-images.githubusercontent.com/16311508/27699405-34d3f0da-5cc8-11e7-9b8e-bd29e8cdef64.jpg)
Ever since I uploaded an addon to the workshop(2 Days ago), whenever I open gmoshui this happens.. I'm using v2.2.1 Alpha and I tried reinstalling it to no avail..

**Comment by FPtje** [comment]
A fix won't be coming, but you can fix your gmoshui by performing this workaround:

Open regedit, go to this path: `HKEY_CURRENT_USER\SOFTWARE\FPtje\gmoshui\workshoptools`. Remove the `lastworkshopid` entry.

See this post for why I'm not supporting this anymore:
https://github.com/FPtje/gmosh/issues/18#issuecomment-274351929
