### ISSUE TITLE
Cannot seem to upload, says there's no addon?

### ISSUE THREAD

**Issue by epicmarkvan** [FPtje/gmosh#21]
Trying to upload with Gmosh but it's saying there's no addon/it can't detect the addon? I'm very confused.

**Comment by FPtje** [comment]
You need an `addon.json` file. Please see the readme.

**Comment by epicmarkvan** [comment]
I do have a .json, I made it with the Gmod program. :/

**Comment by epicmarkvan** [comment]
![untitled](https://user-images.githubusercontent.com/16311169/49014614-b9198280-f14e-11e8-9970-3a35f2323ea4.png)

**Comment by FPtje** [comment]
What does gmosh say precisely? What are the contents of addon.json?

**Comment by epicmarkvan** [comment]
addon.json is
`{
    "description": "A simple weapon repack from various authors for convenient use on my server.",
    "ignore": [
        "*.psd",
        "*.vcproj",
        "*.svn*"
    ],
    "logo": "C:/Users/Mark/Downloads/weaponlogo.jpg",
    "tags": [
        "roleplay",
        "fun"
    ],
    "title": "Halo Weapon Repack",
    "type": "weapon"
}`

And Gmosh says 
![untitled2](https://user-images.githubusercontent.com/16311169/49014900-9471da80-f14f-11e8-9dbb-8262124a483a.png)

**Comment by epicmarkvan** [comment]
> That's a GMPublish error. Might be file permission related.

I set it to run as Administrator and it still doesn't work.



> Yeah, but what if gma creation fails? Could you copy paste the entire message?

Above the previous message it says "Compressing to temporary GMA file...
Publishing GMA file to workshop..."
So it seems to succeed.

**Comment by FPtje** [comment]
TBH I don't know what's going on. You could try running the `gmosh` command in the addon of the folder using `cmd`, but I don't think it'll yield a different result. Maybe you can try creating a GMA to see if there's anything wrong with that.
