### ISSUE TITLE
Won't let me install? (OSX Problem)

### ISSUE THREAD

**Issue by CommanderBanana** [FPtje/gmosh#8]
Alright, so I've been trying to get gmosh on my mac and apperently it doesn't want to work. When I open up the install.command it wants me to put in the admin password. However, when I try to type, it won't let me type and I get it wrong every single time 

Here it is:
WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
Sorry, try again.
Password:

**Comment by FPtje** [comment]
I can't break sudo with gmosh. Note that your sudo password may differ from your regular password.

**Comment by FPtje** [comment]
I'm closing this issue, but you can keep posting.
